# Copy this template to a separate file, and do NOT commit it to your repository!

# Your discord bot token
# You can find documentation on how to set up a Discord app and Bot account from the link below.
# https://discordpy.readthedocs.io/en/latest/discord.html
bot_token: <BOT_TOKEN>

# Your twitter API bearer token
# This only uses tweet querying endpoints on twitter's v2 API. Documentation linked below.
# https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens 
twitter_bearer_token: <TWITTER_BEARER_TOKEN>

# This is the twitter account to channel relay mapping where you can configure which twitter
# accounts will have tweets relayed to which channels. This is a one-to-many mapping so
# you can relay the same tweet to multiple locations. The twitter name does not have the @ sign.
#
# You can get the channel ID by setting up the "developer mode" flag in Discord, right-clicking
# the channel in question, and clicking "copy ID".
# 
# Here is an example configuration
#
# twitter_relay_map:
#   DragonRealms:
#     - 998877665544332211
#     - 112233445566778899
#   taylorswift13:
#     - 192837465564738291
#
twitter_relay_map:
  DragonRealms:
    - <CHANNEL_ID>

# This bot uses sqlite3 to cache seen tweet ids to avoid repeating itself.
# The directory structure must exist. If the file does not exist, the bot will create it.
sqlite3_database_path: /path/to/db

# Path to the Google service account that will have access to the events calendar
# Learn more on how to create a service account from the link below.
# https://cloud.google.com/iam/docs/service-accounts
google_credentials: /path/to/creds.json


# Google Sheets notification map. Works like the twitter map above, more or less.
# 
# The google calendar ID can be found by going to the calendar settings, then 
# under "Integrate Calendar". It should be the first field.
#
# Here is an example configuration. Calendar names are arbitrary.
# "When" is how long before the event to send the reminder, with 0 being at event time.
#
# reminder_relay_map:
#   TavernTroupe:
#     calendar_id: someurl@group.calendar.google.com
#     channels:
#       - 112233445566778899
#       - 998877665544332211
#     when:
#       - 0
#       - 60
#   SomeOtherCalendar:
#     ...
#
reminder_relay_map:
  ReminderName:
    calendar_id: someurl@group.calendar.google.com
    channels:
      - <CHANNEL_ID>
    when:
      - <MINUTES>
