# Copy this template to a separate file, and do NOT commit it to your repository!

# ======================
#     GENERAL CONFIG
# ======================

# Your discord bot token
# You can find documentation on how to set up a Discord app and Bot account from the link below.
# https://discordpy.readthedocs.io/en/latest/discord.html
bot_token: <BOT_TOKEN>

# This bot uses sqlite3 for various parts of its functionality.
# The directory structure must exist. If the file does not exist, the bot will create it.
sqlite3_database_path: /path/to/db

# Where to log output
logging_path: bot.log



# ======================
#     TWITTER CONFIG
# ======================

# Enables twitter functionality. If false, twitter configuration is not required.
enable_twitter: True

# Your twitter API bearer token
# This only uses tweet querying endpoints on twitter's v2 API. Documentation linked below.
# https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens 
twitter_bearer_token: <TWITTER_BEARER_TOKEN>

# This is the twitter account to channel relay mapping where you can configure which twitter
# accounts will have tweets relayed to which channels. This is a one-to-many mapping so
# you can relay the same tweet to multiple locations. The twitter name does not have the @ sign.
#
# You can get the channel ID by setting up the "developer mode" flag in Discord, right-clicking
# the channel in question, and clicking "copy ID".
# 
# Here is an example configuration
#
# twitter_relay_map:
#   DragonRealms:
#     - 998877665544332211
#     - 112233445566778899
#   taylorswift13:
#     - 192837465564738291
#
twitter_relay_map:
  DragonRealms:
    - <CHANNEL_ID>


# =======================
#     CALENDAR CONFIG
# =======================

# Enables google calendar functionality. If false, google calendar configuration is not required
enable_calendar: True

# Path to the Google service account that will have access to the events calendar
# Learn more on how to create a service account from the link below.
# https://cloud.google.com/iam/docs/service-accounts
google_credentials: /path/to/creds.json


# Google Sheets notification map. Works like the twitter map above, more or less.
# 
# The google calendar ID can be found by going to the calendar settings, then 
# under "Integrate Calendar". It should be the first field.
#
# Here is an example configuration. Calendar names are arbitrary.
# "when" is how long before the event to send the reminder, with 0 being at event time.
# "ping" will have the reminder do a @here in the channel if set to True.
#
# reminder_relay_map:
#   TavernTroupe:
#     calendar_id: someurl@group.calendar.google.com
#     ping: False
#     channels:
#       - 112233445566778899
#       - 998877665544332211
#     when:
#       - 0
#       - 60
#     ping:
#       - @here
#   SomeOtherCalendar:
#     ...
#
reminder_relay_map:
  ReminderName:
    calendar_id: someurl@group.calendar.google.com
    ping: False
    channels:
      - <CHANNEL_ID>
    when:
      - <MINUTES>


# =======================
#      PETPIC CONFIG
# =======================

# Enables petpic functionality
enable_petpic: True

# Photos root path
petpic_root_path: path/to/photos/directory


# =======================
#       FUN CONFIG
# =======================

# Enables compliments, jokes, and other silly things.
enable_fun: True


# =======================
#     DRLOGGER CONFIG
# =======================

# Enables drlogger functionality, if false drlogger configuration is not required
enable_drlogger: False

# The account to which you want this bot to connect to for the purposes of running logs.
# This bot makes use of the tintin++ client, but has its own EACCESS protocol implementation
# and scripts/functions to apply, ported/stolen from https://github.com/dylb0t/dr-tin
#
# WARNING: YOU ARE SUPPLYING ACCOUNT CREDENTIALS. READ THE CODE AND USE AT YOUR OWN RISK.
dr_account:
  username: <ACCOUNT_NAME>
  password: <ACCOUNT_PASSWORD>
  character: <CHARACTER_NAME>

# A list of authorized discord users who can use this dangerous feature.
log_authorized_users:
  - <DISCORD_USER_ID>

# The channel to upload logs.
log_upload_channel: <CHANNEL_ID>

# The name template for the uploaded file. These will be appended with the date.
# If prefix is "meeting_notes", the output file may look like:
#   meeting_notes_20201123-221530.txt
log_filename_prefix: meeting_notes

