# Copy this template to a separate file, and do NOT commit it to your repository!

# Your discord bot token
# You can find documentation on how to set up a Discord app and Bot account from the link below.
# https://discordpy.readthedocs.io/en/latest/discord.html
bot_token: <BOT_TOKEN>

# Your twitter API bearer token
# This only uses tweet querying endpoints on twitter's v2 API. Documentation linked below.
# https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens 
twitter_bearer_token: <TWITTER_BEARER_TOKEN>

# This is the twitter account to channel relay mapping where you can configure which twitter
# accounts will have tweets relayed to which channels. This is a one-to-many mapping so
# you can relay the same tweet to multiple locations. The twitter name does not have the @ sign.
#
# You can get the channel ID by setting up the "developer mode" flag in Discord, right-clicking
# the channel in question, and clicking "copy ID".
# 
# Here is an example configuration
#
# twitter_relay_map:
#   DragonRealms:
#     - 998877665544332211
#     - 112233445566778899
#   taylorswift13:
#     - 192837465564738291
#
twitter_relay_map:
  DragonRealms:
    - 000000000000000000

# This bot uses sqlite3 to cache seen tweet ids to avoid repeating itself.
# The directory structure must exist. If the file does not exist, the bot will create it.
sqlite3_database_path: /path/to/db